name: '${name}'
version: '${version}'
main: '${main}'

authors:
  - Drak

folia-supported: true

depend:
  - BukkitOfUtils

commands:
  build:
    description: 'Toggle build mode'
    permission: 'buildmode.command.build'
    aliases:
      - buildmode